### ISSUE TITLE
Strange 24 Hour Pattern in Temperature RMSE

### ISSUE THREAD

**Issue by leanderloew** [google-research/neuralgcm#106]
Hey, I have observed a strange 24-hour pattern in the RMSE on temperature for the deterministic and the stochastic model. Is this to be expected? 

This is RMSE averaged over all 00z forecasts initialized in January 2023. It uses the deterministic model, but I have observed the same pattern using the stochastic model. You can see the pattern is more pronounced over the continental us area.

<img width="720" alt="Screenshot 2024-07-26 at 14 28 10" src="https://github.com/user-attachments/assets/39183fbe-4ec0-4412-87e9-30d5c9925630">

**Comment by leanderloew** [comment]
Ok, you can see the same patterns also on weather-bench for the EPS model, so not a specific issue with ngcm most probably.

**Comment by shoyer** [comment]
For the record, my guess is that this is related to the data assimilation of window of ERA5, which goes from -3 to +9 and +9 to +21 UTC. Inside each 12 hour window, dynamics follow ECMWF's simulation model, which is easier to predict that the real world.
