### ISSUE TITLE
Fully document the internal state of the NeuralGCM models on sigma coordinates

### ISSUE THREAD

**Issue by shoyer** [google-research/neuralgcm#11]
This is important for users who want to manipulate it directly (e.g., for https://github.com/google-research/neuralgcm/issues/8).

**Comment by weatherforecasterwhai** [comment]
Would you please open a test document version at first?
Just show some important suggestions. 
Don't need a "full" document. That's too long to wait. 
It's not so easy to understand codes turning from Pytorch to  JAX and haiku. 
Thank you.
