### ISSUE TITLE
Get daily/monthly output

### ISSUE THREAD

**Issue by ShihengDuan** [google-research/neuralgcm#117]
Thanks for the demo notebook. I'm trying to understand what is the output time steps. When we set the ```inner_steps=24```, is the output instantaneous values or daily averages (I guess it is instantaneous)? Is there a way to aggregate the output to daily or monthly time step?

**Comment by shoyer** [comment]
> Thanks for the demo notebook. I'm trying to understand what is the output time steps. When we set the `inner_steps=24`, is the output instantaneous values or daily averages (I guess it is instantaneous)?

This is correct.

> Is there a way to aggregate the output to daily or monthly time step?

We currently do not have built-in support for any aggregation. You can do this yourself using a Python loop or jax.lax.scan with `inner_steps=1`.
