### ISSUE TITLE
Seems there's no P-E in the output according to running demo notebook. How could we add P-E in the output?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#12]
Thank you for your demo notebook, and it runs ok.
But it seems there's no P-E in the output.
 And I could find the right place or function to add P-E.
So, would you please help me how to add P-E in the output?
Thank you very much!

**Comment by shoyer** [comment]
Good question! I don't think this is accessible from the stable API yet. We will look into this.

**Comment by weatherforecasterwhai** [comment]
Thank you,sir!
I really can't get those settings after reading the opening codes.
So, please open a document as quickly as possible.

I've read at least 3 papers about AI data assimilation method under your name.
I guess you must be adding data assimilation to the neuralgcm.
Then it's really an exciting new revolutional model.

**Comment by MinchanJeong** [comment]
@yaniyuval Your code indeed generated P-E values (Although I did not validate them)! Thank you for sharing your intuition.

**Comment by HamidPahlavan** [comment]
Thanks @yaniyuval for sharing this piece of code. It is very useful and might be worth adding to the documentation.

**Comment by ShihengDuan** [comment]
Is it possible to add two ```StochasticPhysicsParameterizationStep.diagnostics_module ```?
