### ISSUE TITLE
Where can I find the "Extra Features" for Physics Parameterization or Encoder/Decoder?

### ISSUE THREAD

**Issue by snumuchan** [google-research/neuralgcm#120]
I want to compare some of NeuralGCM's features with those of other models, so I aim to match the variables as closely as possible. I have found ERA5 data and some extra features (like sea surface temperature and sea ice cover) from Figures C5 and D8 of Appendices. However, I am unable to locate others such as orography, incident solar radiation, sin/cos (lon/lat), learned surface features, and the land-sea mask.

While I noticed that variables like incident solar radiation and the land-sea mask are available in ERA5 single-level data, I would like to access the exact data used to train some of the pre-trained models, such as "neural_gcm_dynamic_forcing_deterministic_1_4_deg.pkl." Alternatively, I would appreciate guidance on how this data was generated, for example, if the land-sea mask used in pre-training was derived from ERA5 single-level land-sea mask and interpolated using a spherical harmonic function.

Additionally, I am still unable to find the orography/learned surface features data or understand how the sin/cos (lon/lat) data were created. Could you please provide more information on where to find these data or how they were generated?

Thank you for your help!

**Edit (2024.09.05 03:00 UTC):**
I found a way to extract the orography from the model from [this GitHub issue comment](https://github.com/google-research/neuralgcm/issues/8#issuecomment-2065479312). Is the "learned_positional_features" the same as the learned surface features? Additionally, I found "model._structure.specs.aux_features['xarray_dataset']['land_sea_mask']." Is this the land-sea mask that was used for pre-training?

![image](https://github.com/user-attachments/assets/bc7821c9-888b-4539-9921-819ef2f5a240) Fig.C5 Extra features
![image](https://github.com/user-attachments/assets/354ac339-0a30-4ef4-9dd8-2e5f122da382) Fig.D8 Extra features

**Comment by kochkov92** [comment]
Hi @snumuchan 

Thanks for your question! You are correct - some of the features such as `orography` and `land_sea_mask` are loaded from ERA5 data [at the same resolution of the model, i.e. conservatively regridded from the original ERA5]. These values are passed as is using [this feature module](https://github.com/google-research/neuralgcm/blob/1d2fb58058b437aa083392f3289bbd47fae98310/neuralgcm/features.py#L672).

`sin/cos` and `incident solar radiation` are features that are computed from the time and lon/lat variables, which are available from grid specification and simulation time which is one of the evolved model variables. Corresponding feature modules that outline how this is done are [here](https://github.com/google-research/neuralgcm/blob/1d2fb58058b437aa083392f3289bbd47fae98310/neuralgcm/features.py#L353) and [here](https://github.com/google-research/neuralgcm/blob/1d2fb58058b437aa083392f3289bbd47fae98310/neuralgcm/features.py#L209).

Learned surface features are not loaded from any dataset, they represent some of the trainable parameters. Their final values can be extracted from the checkpoints.

Other features (sea ice cover, and sea surface temperature are updated dynamically in annual/decadal simulations or kept fixed at timedelta = 0 for weather forecasting. We use [forcing modules](https://github.com/google-research/neuralgcm/blob/1d2fb58058b437aa083392f3289bbd47fae98310/neuralgcm/forcings.py#L85) to pass that data.

I hope this helps!

**Comment by snumuchan** [comment]
Thank you very much, @kochkov92! Your additional information really helpful. Thanks again for your time and assistance!

**Comment by ShihengDuan** [comment]
Hi @kochkov92 I have a follow-up question about the solar radiation. Does it provide the same value for the same day in different years (i.e., June 29 in 2017 and 2018 would have similar values)? Basically it represents the seasonality. Is my understanding correct?
