### ISSUE TITLE
What's the difference between the two .pkl versions with two different dates: 03_04_2024 and 04_30_2024?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#126]
Hi, 
Really congratulations for the paper publishing on Nature!

Once I noticed the paper on Nature, I returned to the neuralGCM again.
And I found two different .pkl versions from gs://gresearch/neuralgcm/, with
 two different dates: 03_04_2024 and 04_30_2024. 
I can't remember which one I used before.
So, I wonder, what's the differnce between them?

Thank you!

**Comment by weatherforecasterwhai** [comment]
Well, I download the two 0.7 .pkl versions, and I found the .pkl from 04_30_2024 is a little larger than the older one.
But the model_config_str and params are the same.
Will the 04_30_2024 version be better than the older one in forecasting?

**Comment by shoyer** [comment]
These are the same model checkpoint, but I believe only the most recent one will work with the current release of the neuralgcm code.

**Comment by weatherforecasterwhai** [comment]
Thank you!
