### ISSUE TITLE
Idealized Simulations

### ISSUE THREAD

**Issue by snumuchan** [google-research/neuralgcm#132]
I’m curious about the possibility of running idealized simulations, such as aquaplanet or beta-plane configurations, using your model. From my understanding, the dynamical core solves differential equations, so it should be possible to run it under such idealized setups.

My main question is whether it is feasible to remove elements like orography, land-sea masks, or other embedded features and still apply the physical parameterizations learned from the pre-trained model. For example, could we set up an aquaplanet simulation at a 0.7-degree horizontal resolution, using the dynamical core along with the pre-trained physical parameterizations, even without the geographical constraints?

Thank you for your help!

**Comment by yaniyuval** [comment]
Hi @snumuchan,
In principle, we could remove orography etc. 
However, our current models include a location-specific embedding vector for each horizontal grid point. This embedding aim is to learn unresolved features (e.g., subgrid orography etc.). Therefore, the current models will likely not work well in idealized scenarios. With that said, one could train (we did that) a model that does not include such embedding, and I would guess that such a model would be suitable for aquaplanet experiments.

**Comment by snumuchan** [comment]
Thank you for the detailed answer, @yaniyuval.

From what I understand, the surface embeddings module in the model (as shown in the figure below) aligns with what you mentioned about the learned embedding vectors for each grid point.
![379052123-2676c054-b9f3-47b6-bf29-6c43249752db](https://github.com/user-attachments/assets/c37f341b-a054-4ca8-bdfc-9b8e0f83b62f)

I’d like to confirm if it would be feasible to adjust the model for idealized simulations. Specifically, would it be possible to remove or mask components such as the [Land (NN)] output (e.g., setting the embeddings related to land to zero or having them produce zero output)?

Would such modifications still allow the physical parameterizations to function properly, or does the overall optimization process depend heavily on the existence and interaction of these surface embeddings?

Looking forward to your insight!

**Comment by yaniyuval** [comment]
Hi @snumuchan,

For having a proper model that could run idealized simulations (that do not include the positional embeddings) you would need to re-train a model. 
I don't see how you could adjust the existing model to do that.

**Comment by snumuchan** [comment]
Thank you for your answer, @yaniyuval.
