### ISSUE TITLE
Two problems:at sim_time 0, geopotential seems physically wrong, and p_minus_e unit problem. 

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#14]
Hi, sir
1、 At sim_time 0, geopotential at 500hPa, seems physically wrong. When the interval is 5, it's still not so bad (geopotential/100):
![sim_time_0_500hpa_geopotential_interval5](https://github.com/google-research/neuralgcm/assets/162259387/f9d3ce5f-ed16-458a-93a7-113bdd62d1a8)

But, when the interval is 2, it's much worse:
![sim_time_0_500hpa_geopotential_interval2](https://github.com/google-research/neuralgcm/assets/162259387/d47b7e6a-7471-4c5b-ab39-a7faabc1ef83)

But in other sim_time, it's physically ok. I don't know why. Please help me with this.

2、The p_minus_e unit is set as 'diagnostics': {'P_minus_E_cumulative': 'kg / (meter**2)'}
In weather forecasting operation, we often use rain gauge unit :mm.
So, in a square, the p_minus_e unit should be changed to mm by multiplying 1000.
But, the p_minus_e output seems no need to multiply 1000, or it's too large.
Please help me again.

Thank you!

**Comment by yaniyuval** [comment]
About the P-E unit problem you mentioned. 
If you want to change the units to mm, you also need to divide by the density of water ~997 kg / meter**3 which would roughly leave the results unchanged.

**Comment by shoyer** [comment]
I don't think we fully understand why goepotential looks bad for the first few time steps. My guess is that this may be related to limitations of the encoder/decoder in our model.
