### ISSUE TITLE
Please help me again to set outputing tendencies of variables?Thank you!

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#29]
Hi, 

1.In your neuralGCM paper, C.4 says "In all models we predict tendencies of the wind vector, 
temperature and moisture species at all levels." 
2.In appendix E, both "dynamic tendencies and machine learning tendencies are computed at every time step".

So, can these tendencies be output? Would yo please help me again to set it?

Thank you very much for your attention again!

**Comment by weatherforecasterwhai** [comment]
@kochkov92 @shoyer @yaniyuval Please pay attention to help me, thank you!

**Comment by yaniyuval** [comment]
Hi, 

Currently there is no easy way to get these tendencies. In future work we might include the ability to easily access the predicted tendencies from the NN.

**Comment by weatherforecasterwhai** [comment]
@yaniyuval Thank you, sir! 
The tendencies are related to the "hybrid" of dynamic and learned parameterization, which is really confusing. Sorry, I asked 3 questions about the title of neuralGCM paper. I can't understand enough how does they "hybrid"  together? Just like in #52, #24

**Comment by weatherforecasterwhai** [comment]
The third version paper indeed has a fig seperate the tendencies.
So, they can be seperated, but not easy to do yet as you said.
