### ISSUE TITLE
Thank you for opening neuralGCM codes! Need more users' guide or documents!

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#4]
Need more user guides or documents! Especially for:
1. Why using p minus e instead of precipitation directly? How could we use p minus e ?
2. Would you please open the trained checkpoints to download like GraphCast for easy using?
3. How to use these codes? As a poor fresh man, I can't use these codes after reading your appendix in the paper.
     I even couldn't understand enough the neural network used in the paper without pictures.
Please help me with more users' guide! Thank you!

**Comment by shoyer** [comment]
Hi @weatherforecasterwhai,

Thanks for your interest in NeuralGCM!

To answer your questions briefly:

- Predicting P minus E is a limitation of our current model architecture, which was not trained to predict precipitation directly. See the paper for more details, but we do anticipate training models to predict precipitation in the future.
- As you have probably noticed, this repository is still a work in progress! We have an initial demonstration of how to run NeuralGCM now available -- see the README and demo notebook for more details.

Cheers,
Stephan

**Comment by weatherforecasterwhai** [comment]
Thank you very much! You are really kind to open your newest work on github!
I'll try to follow your new demo to use.



At 2024-03-08 08:07:59, "Stephan Hoyer" ***@***.***> wrote:

Hi @weatherforecasterwhai,

Thanks for your interest in NeuralGCM!

To answer your questions briefly:

Predicting P minus E is a limitation of our current model architecture, which was not trained to predict precipitation directly. See the paper for more details, but we do anticipate training models to predict precipitation in the future.
As you have probably noticed, this repository is still a work in progress! We have an initial demonstration of how to run NeuralGCM now available -- see the README and demo notebook for more details.

Cheers,
Stephan
