### ISSUE TITLE
How many Ensemble Members for Neural GCM?

### ISSUE THREAD

**Issue by leanderloew** [google-research/neuralgcm#45]
Hey, first of all, thanks for the great work and open-sourcing everything! 

In the paper, how many ensemble members are used for the NeuralGCM-ENS model for inference? The only clue I could find: 

> Forecasts from individual ensemble members from ECMWF-ENS and NeuralGCM-ENS over regions of interest, including predicted tracks of Hurricane Laura from each of the 50 ensemble members

So, can I assume that all performance evaluations are done on 50 ensemble members for NeuralGCM-ENS ? Have you done any ablation studies for increasing the number of members?

Thanks for the help!

**Comment by shoyer** [comment]
We use 50 ensemble members for all the results in the paper, but the you can run NeuralGCM-ENS for as many or few ensemble members as desired, simply by supplying a different RNG seed when making a forecast.

Debiased scores like the "fair CRPS" used in WeatherBench do not depend on the ensemble size (on average), but other metrics will. We haven't look at them.
