### ISSUE TITLE
How does the dynamic part and learned parameterization part "hybrid" together ?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#52]
Hi,

Tracing through the demo every step, neuralGCM seems to run
1.the learning steps to parameterization all together, 
2.then filter,tranforms,equations,features,
3.start with dinosaur radiation and shallow water states,
4.again to neuralGCM correctors,
5.at last to dinosaur other steps.

If the above steps are true, I want to ask more questions about them:
1. Does it mean, only the 4th step, neuralGCM correctors modify the 
"shallow water state" of dinosaur? And why corrects shallow water state
instead of primitive equation state? 

2.In the 1st step of neuralGCM, the diagnostic of p_e already finished,
do other diagnostic and prognostic steps of dinosaur count p_e again?
Maybe p_e should be added by sub-grid parameterization and large scale 
process of dinosaur? Just like your neuralGCM paper fig1, dynamic part and learned 
physical parameterization part work at the same time and then adds together 
to the output.  

3.In physical numeric models like WRF, dynamics run first and then physics parameterization runs.
What does dinosaur do after neuralGCM?

4."Forcing" part, at the beginning, it relates to sea ice cover and sea surface temperature.
Then in the neuralGCM.forcing.py, what are "dynamic data forcing " and "persistence data forcing"?

Thank you again and again. NeuralGCM is really excellent in prediction, but I'm really confused.
Please help me.

@kochkov92 @shoyer @langmore @yaniyuval

**Comment by shoyer** [comment]
> 1. Does it mean, only the 4th step, neuralGCM correctors modify the
>    "shallow water state" of dinosaur? And why corrects shallow water state
>    instead of primitive equation state?

No, we solve the full primitive equations for NeuralGCM. The shallow water equation is just used a reference problem for Dinosaur.

> 2.In the 1st step of neuralGCM, the diagnostic of p_e already finished,
do other diagnostic and prognostic steps of dinosaur count p_e again?
Maybe p_e should be added by sub-grid parameterization and large scale
process of dinosaur? Just like your neuralGCM paper fig1, dynamic part and learned
physical parameterization part work at the same time and then adds together
to the output.
>
> 3.In physical numeric models like WRF, dynamics run first and then physics parameterization runs.
What does dinosaur do after neuralGCM?

As described in https://github.com/google-research/neuralgcm/issues/66#issuecomment-2098239684, you can track the configuration via the Gin config string.

> 4."Forcing" part, at the beginning, it relates to sea ice cover and sea surface temperature.
> Then in the neuralGCM.forcing.py, what are "dynamic data forcing " and "persistence data forcing"?

These are only used for training models. When making forecasts, you can control how forcings are used by which data you pass in: https://neuralgcm.readthedocs.io/en/latest/trained_models.html#advancing-in-time

**Comment by weatherforecasterwhai** [comment]
Thank you. You're really kind to help me.
Most of my questions have answers in the thrid version of neuralGCM paper. 
However, I always sleep on the origional version of neuralGCM paper and codes until yesterday.
So, thank you for your goodness. Please help me with the new issues. 
The more I read the third version, the more I want to learn nueralGCM to clear.
