### ISSUE TITLE
Demo Notebook Not Found

### ISSUE THREAD

**Issue by leanderloew** [google-research/neuralgcm#55]
I see the example notebook was moved from the top level to /docs. However, I can't access this new notebook on colab. It first requires a login and then shows Notebook not found.

**Comment by leanderloew** [comment]
Ah ok so I can find the notebook at https://colab.research.google.com/github/google-research/neuralgcm/blob/main/docs/inference_demo.ipynb

**Comment by shoyer** [comment]
Sorry about that!

I moved the example notebook into our [HTML docs](https://neuralgcm.readthedocs.io) where it should be quicker to load and next to other guidance on how to use NeuralGCM.

Let me know if anything else comes up here!

**Comment by leanderloew** [comment]
Sorry, I didn't phrase this correctly. What I actually meant was that the link in the readme is broken. I think it should be this link instead https://colab.research.google.com/github/google-research/neuralgcm/blob/main/docs/inference_demo.ipynb

**Comment by shoyer** [comment]
Ah, thanks! This will be fixed shortly after submitting https://github.com/google-research/neuralgcm/pull/51
