### ISSUE TITLE
Difficulties Replicating Results Outside of Colab

### ISSUE THREAD

**Issue by leanderloew** [google-research/neuralgcm#56]
I am having problems replicating the results of the demo notebook locally. 
These are the results from colab:
![image](https://github.com/google-research/neuralgcm/assets/34112996/9d6839d6-0c1b-420a-bf0f-de4a6d9770d0)

These are the results when I run it locally: 
<img width="756" alt="Screenshot 2024-05-02 at 13 52 37" src="https://github.com/google-research/neuralgcm/assets/34112996/df11cd97-67f7-4369-90bb-bafa5ed1e080">

I was extra careful to install all python packages in the same version. It is running on GPU in both cases. I'm working with Docker. Any help would be greatly appreciated.

**Comment by shoyer** [comment]
Oh wow, that does look rather different!

We have made a couple of small changes to the NeuralGCM & Dinosaur packages recently, so to double check, try uninstalling and reinstalling them from scratch?

It that doesn't resolve the issue, it would be amazing if you could track down where the discrepancy first occurs. For example, does it arise in the [encoded model state](https://neuralgcm--51.org.readthedocs.build/en/51/trained_models.html#encoded-model-state) or does it require advacing in time?

**Comment by leanderloew** [comment]
Hey, thanks for the help first of all! I have been re-building the docker image constantly, using the newest version of your packages, so I think this part should be fine.

A tiny difference first appears after regridding but that should be float issues. However, the initial_state is decently different and the difference then explodes when advancing the steps.

Now, the most surprising thing running on CPU seems to have basically fixed the issue.
<img width="577" alt="Screenshot 2024-05-02 at 18 52 41" src="https://github.com/google-research/neuralgcm/assets/34112996/6e674b1d-418a-4440-aff9-9d61a2d904b5">

Also, I plotted the average of vorticity while advancing the steps you can see here: 
First one on colab: 
![Untitled (1)](https://github.com/google-research/neuralgcm/assets/34112996/34a81f77-f080-4a38-bc4e-321ef4477ed7)

The second one using local GPU (which is an RTX 4000) 
<img width="444" alt="Screenshot 2024-05-02 at 16 30 56" src="https://github.com/google-research/neuralgcm/assets/34112996/6933efb6-a418-48ca-8be0-7d096e2be2f7">

Final one running on CPU locally, still quite a difference to the first one but directionally correct. 
<img width="444" alt="Screenshot 2024-05-02 at 16 31 23" src="https://github.com/google-research/neuralgcm/assets/34112996/233d104b-84ab-4176-b2fa-a7f49db1e726">

To me this indicates some issues with the Jax configuration, however the jax.config dictionaries are exactly the same. I'm on cuda 12.4 but the same issue appeared on 12.1 as well.

**Comment by shoyer** [comment]
I wonder if this is default matrix-multiplication precision issue. 

Can you try wrapping the computation in a context manager to set float32 precision?
```
with jax.default_matmul_precision('float32'):
   ...
```

**Comment by shoyer** [comment]
Ah, I have a new idea. I think this might be related precision of spherical harmonic transforms ("tensorfloat32" means something different on GPU vs TPU for JAX).

Can you try modifying the model config string in the checkpoint?
```
ckpt['model_config_str'] = ckpt['model_config_str'].replace(
    "RealSphericalHarmonicsWithZeroImag.transform_precision = 'tensorfloat32'",
    "RealSphericalHarmonicsWithZeroImag.transform_precision = 'float32'",
)
```

**Comment by leanderloew** [comment]
Sadly, neither of them (or both) helped. When running the computations jax is also showing this warning. 

`Explicitly requested dtype float64 requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable.`

If i set jax_enable_x64 to True. I get this error: 
`TypeError: lax.conv_general_dilated requires arguments to have the same dtypes, got float64, float32.`

**Comment by shoyer** [comment]
The warnings should be OK. We need to make some updates to our code to silence them: https://github.com/google-research/neuralgcm/issues/57

**Comment by leanderloew** [comment]
Ok, I switched the VM to a t4 GPU and now everything works. Seems to be a problem with RTX gpus. Thanks for the help!
