### ISSUE TITLE
Could you authors please open the codes related to physical consistency in the paper?

### ISSUE THREAD

**Issue by weatherforecasterwhai** [google-research/neuralgcm#70]
The physical consistency part in neuralGCM paper is really great, especially better than other models.
For example, the power spectra and geostrophic wind balance figures are great for weather forecasters.

These codes are not so essential or important compared to neuralGCM itself. 
So, if it's ok, could you please open these codes within neuralGCM too?

Thank you!

**Comment by shoyer** [comment]
Most of the calculating these quantities is open sourced as part of the WeatherBench2 project: https://github.com/google-research/weatherbench2

**Comment by weatherforecasterwhai** [comment]
Yes,however,it’s not easy to use.
I’m using local neuralGCM output netcdf data to compute derived variables,such as vertical velocity. After converting nc data to zarr file format, but running command line still gets error: inconsistent dimensions of time.

**Comment by weatherforecasterwhai** [comment]
I'll learn weatherbench2 more to better understand neuralGCM and other models.
Thank you!
