### ISSUE TITLE
Install Neurealgcm 

### ISSUE THREAD

**Issue by ZiAngGu1** [google-research/neuralgcm#87]
When i want to download the dependencies on my local machine use the command 
pip install neuralgcm
it will tell me 
ERROR: Could not find a version that satisfies the requirement neuralgcm (from versions: none)
ERROR: No matching distribution found for neuralgcm
I also tried goggle colab but it also doesn't work
I wonder how should i solve this issue

**Comment by shoyer** [comment]
Which version of Python are you using? NeuralGCM requires Python 3.10 or later.

**Comment by ZiAngGu1** [comment]
My python version is 3.8 
I will try to update the python version
Thank for your time!
